name:  gearman
description: a Gearman Protocol Implementation in Dart
version: 0.1.0-dev
authors: 
 - Andrew Tsao <caoshiwei@gmail.com>
homepage: https://github.com/AndrewTsao/gearman_dart
dependencies:
  logging: any
#  unittest: { sdk: unittest }
